parameters:
#    karoline_kroiss_web_page.example.class: KarolineKroiss\WebPageBundle\Example

services:
#    karoline_kroiss_web_page.example:
#        class: %karoline_kroiss_web_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
