services:
    admin.exhibition:
        class: KarolineKroiss\ExhibitionBundle\Admin\ExhibitionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Ausstellungen", label: "Ausstellungen" }
        arguments:
            - ~
            - KarolineKroiss\ExhibitionBundle\Entity\Exhibition
            - ~
        calls:
            - [ setTranslationDomain, [KarolineKroissExhibitionBundle]]
