karoline_kroiss_exhibition:
    resource: "@KarolineKroissExhibitionBundle/Resources/config/routing.yml"
    prefix:   /

karoline_kroiss_gallery:
    resource: "@KarolineKroissGalleryBundle/Resources/config/routing.yml"
    prefix:   /

karoline_kroiss_art_gallery:
    resource: "@KarolineKroissArtGalleryBundle/Resources/config/routing.yml"
    prefix:   /

karoline_kroiss_web_page:
    resource: "@KarolineKroissWebPageBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /arg7G=bv72mP95

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /arg7G=bv72mP95

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

