<?php

namespace KarolineKroiss\WebPageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CmsPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsPageRepository extends EntityRepository
{

    /**
     * @param $name
     * @return null|object
     */
    public function getPageByName($name)
    {
        return $this->findOneBy(['name' => $name]);
    }
}
