karoline_kroiss_gallery_homepage:
  path: /
  defaults: { _controller: KarolineKroissGalleryBundle:Gallery:firstGallery }

karoline_kroiss_gallery_by_year:
  path:  /bilder/{type}/{year}
  defaults: { _controller: KarolineKroissGalleryBundle:Gallery:showByTypeAndYear }

karoline_kroiss_gallery_by_type:
  path:  /bilder/{path}
  defaults: { _controller: KarolineKroissGalleryBundle:Gallery:showSimilar }

#karoline_kroiss_gallery_refactor:
#  path:  /refactor
#  defaults: { _controller: KarolineKroissGalleryBundle:Gallery:refactor }
