karoline_kroiss_gallery_homepage:
  path: /
  defaults: { _controller: KarolineKroissGalleryBundle:Gallery:firstGallery }

karoline_kroiss_gallery_by_year:
  path:  /gallerie/{type}/{year}
  defaults: { _controller: KarolineKroissGalleryBundle:Gallery:showByTypeAndYear }

karoline_kroiss_gallery_images_by_gallery_image_themes:
  path:  /bild/{name}
  defaults: { _controller: KarolineKroissGalleryBundle:Gallery:showSimilar }
